[build-system]
requires = [
    "setuptools>=42",
    "numpy",
    "scipy",
    "matplotlib",
    "alive_progress",
    "opencv-python",
    "pixelinkWrapper",
    "pyserial"
]
build-backend = "setuptools.build_meta"